version: '3'
services:
  front-end:
    build:
      context: front-end
      dockerfile: Dockerfile
    image: task5-frontend:latest
    ports:
      - "9000:80"
    depends_on:
      - back-end

  back-end:
    build:
      context: back-end
      dockerfile: Dockerfile
    image: task5-backend:latest
    ports:
      - "5252:5252"
