version: '3'
services:
  front-end:
    build:
      context: front-end
      dockerfile: Dockerfile
    image: task5-frontend:latest
    expose:
      - "9000"
    depends_on:
      - back-end

  back-end:
    build:
      context: back-end
      dockerfile: Dockerfile
    image: task5-backend:latest
    expose:
      - "5252"

  proxy:
    build:
      context: ./proxy
      dockerfile: Dockerfile
    image: task5-proxy:latest
    ports:
      - "80:80"
    depends_on:
      - front-end
      - back-end
